# This workflow automatically tests new commits and pull requests as they come in.
# Note that this does not upload any artifacts, you will need to compile mcMMO manually
# if you wish to create the actual jar.
name: Build

on:
  push:
  workflow_dispatch:
jobs:
  compile:
    name: Maven compiler
    runs-on: ubuntu-latest
    steps:

    # 1. Check out the current working tree
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Setup Java 17 JDK (Adopt)
    - name: Java 17 setup
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-package: jdk
        java-version: '17'


    # 3. Build via Maven 
    - name: Build via Maven
      run: mvn clean package install
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: Guole
        path: ./*
